# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnLn7mLepWHuB3yaYOLIWQ2bjYQDxck8
"""

import pandas as pd


url = "https://github.com/Zulayho06/Maxsus-topshiriq/raw/main/WHO%20COVID-19%20cases.csv"
data = pd.read_csv(url)

print(data.head())

country_data = data[data['Country'] == 'Uzbekistan']

print(country_data)

high_cases = data[data['New_cases'] > 1000]

print(high_cases)